name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Build library
        run: pnpm run build
